import io
import re
import torch
import logging
from PIL import Image
from transformers import VisionEncoderDecoderModel, AutoTokenizer, AutoImageProcessor

logger = logging.getLogger(__name__)

try:
    from math2docx import add_math
except ImportError:
    add_math = None
    logger.warning("math2docx not installed. Equations will be inserted as plain text.")

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
_equation_models = None


def get_equation_models():
    """Lazy initialization of the im2latex model only."""
    global _equation_models
    if _equation_models is not None:
        return _equation_models

    logger.info(f"Loading im2latex model on {DEVICE}...")
    try:
        model_ocr = VisionEncoderDecoderModel.from_pretrained("DGurgurov/im2latex").to(DEVICE)
        tokenizer = AutoTokenizer.from_pretrained("DGurgurov/im2latex")
        image_processor = AutoImageProcessor.from_pretrained(
            "microsoft/swin-base-patch4-window7-224-in22k"
        )
        _equation_models = {
            "model": model_ocr,
            "tokenizer": tokenizer,
            "processor": image_processor,
        }
        logger.info("✅ im2latex loaded successfully.")
        return _equation_models
    except Exception as e:
        logger.error(f"Failed to load equation models: {e}")
        return None


def get_ocr_im2latex(img: Image.Image, models: dict) -> str:
    """Runs the DGurgurov/im2latex model on the image."""
    if img.mode != "RGB":
        img = img.convert("RGB")
    pixel_values = models["processor"](images=img, return_tensors="pt").pixel_values.to(DEVICE)
    generated_ids = models["model"].generate(pixel_values)
    return models["tokenizer"].batch_decode(generated_ids, skip_special_tokens=True)[0]


def refine_with_local_vlm(img: Image.Image, ocr_text: str) -> str:
    """
    Uses the project's existing fallback VLM (SmolVLM) to clean up im2latex output.
    Reuses the already-loaded model from vision_processor — no extra VRAM cost.
    """
    try:
        from src.models.vision_processor import process_image as vlm_process

        prompt = (
            f"The following LaTeX was generated by an OCR model: {ocr_text}\n"
            "Look at the image and correct this LaTeX. "
            "Rules: only extract math, no diagrams or arrows. "
            "Do not use \\begin{align} or & for alignment. "
            "Separate each equation with \\\\. "
            "Return only the raw LaTeX string, no markdown."
        )

        # Convert PIL image to bytes for vision_processor
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        refined = vlm_process(buf.getvalue(), prompt)

        # Strip any model artifacts your fallback VLM tends to emit
        refined = refined.replace("<|end|>", "").replace("<image>", "").strip()
        refined = refined.replace("```latex", "").replace("```", "").replace("$", "")
        return refined if refined else ocr_text

    except Exception as e:
        logger.warning(f"Local VLM refinement failed, using raw im2latex output: {e}")
        return ocr_text


def _sanitize_equations(latex_block: str) -> list[str]:
    """
    Splits and cleans a LaTeX string into individual equation strings.
    Handles the most common im2latex artifacts even without LLM cleanup.
    """
    # Split on double backslash or newline
    parts = re.split(r'\\\\|\n', latex_block)

    cleaned = []
    for eq in parts:
        eq = eq.replace('&', '')
        eq = re.sub(r'\\begin\{[^\}]+\}', '', eq)
        eq = re.sub(r'\\end\{[^\}]+\}', '', eq)
        eq = eq.replace(r'\[', '').replace(r'\]', '')
        # Drop fragments that are clearly just noise (single chars, stray braces)
        eq = eq.strip()
        if eq and len(eq) > 2:
            cleaned.append(eq)

    return cleaned


def extract_equations_from_image(image_bytes: bytes) -> list[str]:
    """Main pipeline: im2latex OCR → local VLM refinement → sanitize."""
    models = get_equation_models()
    if not models:
        return []

    try:
        img = Image.open(io.BytesIO(image_bytes))
        draft_latex = get_ocr_im2latex(img, models)
        refined_latex = refine_with_local_vlm(img, draft_latex)
        return _sanitize_equations(refined_latex)
    except Exception as e:
        logger.error(f"Equation extraction error: {e}")
        return []


def insert_equation_into_docx(doc, inline_shape_element, equations: list[str]):
    """
    Finds the paragraph containing the image and inserts equations directly after it.
    Unchanged from original.
    """
    if not add_math or not equations:
        return

    target_paragraph = None
    for p in doc.paragraphs:
        if inline_shape_element in p._element.xpath('.//wp:inline'):
            target_paragraph = p
            break

    if target_paragraph:
        for eq in equations:
            try:
                new_p = target_paragraph.insert_paragraph_before("")
                target_paragraph._p.addnext(new_p._p)
                add_math(new_p, eq)
            except Exception as e:
                logger.warning(f"Failed to add MathML, falling back to text: {e}")
                new_p.add_run(f"[Equation]: {eq}")