import io
import re
import logging
from PIL import Image
try:
    import torch
    from transformers import VisionEncoderDecoderModel, AutoTokenizer, AutoImageProcessor
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
except ImportError:
    torch = None
    DEVICE = "cpu"

logger = logging.getLogger(__name__)

try:
    from math2docx import add_math
except ImportError:
    add_math = None
    logger.warning("math2docx not installed. Equations will be inserted as plain text.")

_equation_models = None


def get_equation_models():
    """Lazy initialization of the im2latex model only."""
    global _equation_models
    if _equation_models is not None:
        return _equation_models

    logger.info(f"Loading im2latex model on {DEVICE}...")
    try:
        model_ocr = VisionEncoderDecoderModel.from_pretrained("DGurgurov/im2latex").to(DEVICE)
        tokenizer = AutoTokenizer.from_pretrained("DGurgurov/im2latex")
        image_processor = AutoImageProcessor.from_pretrained(
            "microsoft/swin-base-patch4-window7-224-in22k"
        )
        _equation_models = {
            "model": model_ocr,
            "tokenizer": tokenizer,
            "processor": image_processor,
        }
        logger.info("✅ im2latex loaded successfully.")
        return _equation_models
    except Exception as e:
        logger.error(f"Failed to load equation models: {e}")
        return None


def get_ocr_im2latex(img: Image.Image, models: dict) -> str:
    """Runs the DGurgurov/im2latex model on the image."""
    if img.mode != "RGB":
        img = img.convert("RGB")
    pixel_values = models["processor"](images=img, return_tensors="pt").pixel_values.to(DEVICE)
    generated_ids = models["model"].generate(pixel_values)
    return models["tokenizer"].batch_decode(generated_ids, skip_special_tokens=True)[0]


def refine_with_local_vlm(img: Image.Image, ocr_text: str) -> str:
    """
    Uses the project's existing fallback VLM (SmolVLM) to clean up im2latex output.
    Reuses the already-loaded model from vision_processor — no extra VRAM cost.
    """
    try:
        from src.models.vision_processor import process_image as vlm_process

        prompt = (
            f"The following LaTeX was generated by an OCR model: {ocr_text}\n"
            "Look at the image and correct this LaTeX. "
            "Rules: only extract math, no diagrams or arrows. "
            "Do not use \\begin{align} or & for alignment. "
            "Separate each equation with \\\\. "
            "Return only the raw LaTeX string, no markdown."
        )

        # Convert PIL image to bytes for vision_processor
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        refined = vlm_process(buf.getvalue(), prompt)

        # Strip any model artifacts your fallback VLM tends to emit
        refined = refined.replace("<|end|>", "").replace("<image>", "").strip()
        refined = refined.replace("```latex", "").replace("```", "").replace("$", "")
        return refined if refined else ocr_text

    except Exception as e:
        logger.warning(f"Local VLM refinement failed, using raw im2latex output: {e}")
        return ocr_text


def _sanitize_equations(latex_block: str) -> list[str]:
    """
    Splits and cleans a LaTeX string into individual equation strings.
    Handles the most common im2latex artifacts even without LLM cleanup.
    """
    # Split on double backslash or newline
    parts = re.split(r'\\\\|\n', latex_block)

    cleaned = []
    for eq in parts:
        eq = eq.replace('&', '')
        eq = re.sub(r'\\begin\{[^\}]+\}', '', eq)
        eq = re.sub(r'\\end\{[^\}]+\}', '', eq)
        eq = eq.replace(r'\[', '').replace(r'\]', '')
        # Drop fragments that are clearly just noise (single chars, stray braces)
        eq = eq.strip()
        if eq and len(eq) > 2:
            cleaned.append(eq)

    return cleaned


def _extract_equations_with_gemini(image_bytes: bytes, api_key: str) -> list[str]:
    """Uses Gemini to directly extract and format LaTeX equations from an image."""
    try:
        import google.generativeai as genai
        if not api_key:
            logger.error("No API key provided for Gemini equation extraction.")
            return []
            
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel('gemini-2.5-flash-lite')
        img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
        
        prompt = (
            "Extract all mathematical equations from this image. "
            "Return only the raw LaTeX string, separating multiple equations with \\\\. "
            "Do not use markdown blocks, \\begin{align}, or explain anything."
        )
        
        response = model.generate_content([prompt, img])
        
        # --- ADD THESE LINES TO CLEAN GEMINI'S OUTPUT ---
        raw_text = response.text
        raw_text = raw_text.replace("```latex", "").replace("```", "").replace("$", "")
        
        return _sanitize_equations(raw_text)
    except Exception as e:
        logger.error(f"Gemini equation extraction failed: {e}")
        return []

def extract_equations_from_image(image_bytes: bytes, provider: str = "local", api_key: str = None) -> list[str]:
    """Main pipeline: Routes to Gemini or Local (im2latex OCR → local VLM refinement)."""
    if provider.lower() == "gemini":
        logger.info("Routing Equation extraction to Gemini...")
        return _extract_equations_with_gemini(image_bytes, api_key)

    logger.info("Routing Equation extraction to Local (im2latex)...")
    models = get_equation_models()
    if not models:
        return []

    try:
        img = Image.open(io.BytesIO(image_bytes))
        draft_latex = get_ocr_im2latex(img, models)
        refined_latex = refine_with_local_vlm(img, draft_latex)
        return _sanitize_equations(refined_latex)
    except Exception as e:
        logger.error(f"Equation extraction error: {e}")
        return []


def insert_equation_into_docx(doc, target_shape, equations: list[str]):
    """
    Finds the paragraph containing the image and inserts equations directly after it.
    """
    if not equations:
        return

    target_paragraph = None
    
    # 1. target_shape is the <w:drawing> element. We find its parent paragraph <w:p>
    parent_p_elements = target_shape.xpath('./ancestor::w:p')
    if parent_p_elements:
        p_element = parent_p_elements[0]
        # 2. Find the corresponding python-docx Paragraph object
        for p in doc.paragraphs:
            if p._element == p_element:
                target_paragraph = p
                break
    
    if target_paragraph:
        for eq in equations:
            try:
                # Insert a new paragraph
                new_p = target_paragraph.insert_paragraph_before("")
                # Move it to appear immediately AFTER the image's paragraph
                target_paragraph._p.addnext(new_p._p)
                
                # 3. If math2docx is installed, format it properly. Otherwise, fall back to plain text.
                if add_math:
                    add_math(new_p, eq)
                else:
                    new_p.add_run(f"[Extracted Equation]: {eq}")
            except Exception as e:
                logger.warning(f"Failed to add MathML, falling back to text: {e}")
                new_p.add_run(f"[Extracted Equation]: {eq}")

def insert_equation_into_pptx(slide, shape, equations: list[str]):
    """
    Inserts extracted LaTeX equations into a new text box on the PowerPoint slide,
    positioned just below the original image.
    """
    if not equations:
        return

    try:
        from pptx.util import Pt
        
        # Position the text box slightly below the original image
        left = getattr(shape, "left", Pt(100))
        top = getattr(shape, "top", Pt(100)) + getattr(shape, "height", Pt(100)) + Pt(10)
        width = getattr(shape, "width", Pt(300))
        
        # Approximate height based on number of equations
        height = Pt(30 * len(equations))
        
        txBox = slide.shapes.add_textbox(left, top, width, height)
        tf = txBox.text_frame
        tf.text = "[Extracted Equation]:"
        
        for eq in equations:
            p = tf.add_paragraph()
            p.text = str(eq)
            
    except Exception as e:
        logger.error(f"Failed to insert equation text box into PPTX: {e}")